import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout } from "antd";
import { UserProvider } from "./user-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ padding: 0, margin: 0 }}>
        <UserProvider>
          <AntdRegistry>
            <Layout style={{ minHeight: '100vh', fontFamily: 'Hiragino Sans GB' }}>
              {children}
            </Layout>
          </AntdRegistry>
        </UserProvider>
      </body>
    </html>
  );
}
