name: Deploy Next-IMJoye

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{matrix.node-version}}
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: '.'
          REMOTE_HOST: imjoye.chat
          REMOTE_USER: root
          TARGET: '/usr/local/chat/web'
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            cnpm install
            cnpm run build
            pm2 delete nextjs-imjoye
            pm2 start cnpm --name "nextjs-imjoye" -- start